# -*- coding: utf-8 -*-
"""Bursa scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/tys203831/75c60c26862d53adafe01b7ddd7fda3b/bursa-scraper.ipynb
"""
import scripts
import sidebar
import streamlit as st



# main page
st.markdown("# Bursa Stock Scraper")

form = st.sidebar.form(key="input form")
rf,period,interval,confidence_level,include_dividends,exclude_warrant,skipna,submitted,updated = sidebar.sidebar(form)

st.markdown("See original project [here](https://colab.research.google.com/gist/tys203831/75c60c26862d53adafe01b7ddd7fda3b/bursa-scraper.ipynb)")

csvdir = scripts.process_csv.csvDirectory(rf=rf, period=period,interval=interval, 
                                          confidence_level=confidence_level, 
                                          exclude_warrant=exclude_warrant)

if updated:
  csvdir = scripts.process_csv.csvDirectory(rf=rf, period=period,interval=interval, 
                                            confidence_level=confidence_level, 
                                            exclude_warrant=exclude_warrant)
  scripts.refresh_data.refreshData(csvdir, rf=rf, period=period,interval=interval, 
              confidence_level=confidence_level, exclude_warrant=exclude_warrant)

if not submitted:
  last_updated = scripts.set_dataframe.check_update(csvdir, rf=rf, period=period,interval=interval, 
                                            confidence_level=confidence_level, 
                                            exclude_warrant=exclude_warrant)
  scripts.set_dataframe.display_data(csvdir)
  
if submitted:
  csvdir = scripts.process_csv.csvDirectory(rf=rf, period=period,interval=interval, 
                                            confidence_level=confidence_level, 
                                            exclude_warrant=exclude_warrant)
  last_updated = scripts.set_dataframe.check_update(csvdir, rf=rf, period=period,interval=interval, 
                                            confidence_level=confidence_level, 
                                            exclude_warrant=exclude_warrant)
  scripts.set_dataframe.display_data(csvdir)
  
